name: Incare Servicios Médicos
favicon: null
layout_spectrum: 0.36864
typography_spectrum: 0.72496
title: INCARE Servicios Médicos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19171a'
    - '#2881be'
    - '#a8a8a8'
    - '#484649'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.9726751339621842
purpose: []
